version: '3'

services:
  adminer:
    image: dockette/adminer:full-php5
    restart: always
    ports:
      - 8080:80
  dbPostgres:
    image: postgres:11.6-alpine
    restart: always
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: pwd
        POSTGRES_DB: mydb