version: '3'

services:
  adminer:
    image: dockette/adminer:full-php5
    restart: always
    ports:
      - 8080:80
  database:
    build:
      context: database
      dockerfile: "Dockerfile"
    restart: always
    ports:
        - 5432:5432