version: "3"
services:
  database:
    build:
      context: "./Database"
      dockerfile: "Dockerfile"
    restart: always
    volumes:
      - ./Database/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - devops_network

  backend:
    build:
      context: "./Backend_API"
      dockerfile: "Dockerfile"
    restart: always
    ports:
      - 8080:8080
    networks:
      - devops_network

  httpd:
    build:
      context: "./Http_server"
      dockerfile: "Dockerfile"
    restart: always
    ports:
      - 80:80
    networks:
      - devops_network
    
networks:
  devops_network:
